### ISSUE TITLE
Add changes: task 3

### ISSUE THREAD

**Issue by HalfSealHalfCat** [minaev-aa/infa_2020_minaev#1]
[In task 3](https://github.com/minaev-aa/infa_2020_minaev/blob/master/pygame_lab3.1/town.py)

1. Check the correctness of spacing.
2. Add private methods and try inherency.
3. Save the result as .gif.
4. Add some exception handling.

**Comment by minaev-aa** [comment]
1) Пробелы поправил
2) Добавил приватные методы(48, 137)
3) Добавил возможность сохранения gif
Код запуска без gif и с сохранением в gif в отдельном [модуле](https://github.com/minaev-aa/infa_2020_minaev/blob/master/pygame_lab3.1/module/start_save.py)
Сам [gif](https://github.com/minaev-aa/infa_2020_minaev/blob/master/pygame_lab3.1/pic/gif.gif)
4) Добавил исключения, что на вход координат идут только числа(50, 79, 138, 159)
